### ISSUE TITLE
Question: can I make my buttons to fill the whole tab container?

### ISSUE THREAD

**Issue by awedeebawe** [bitomule/SimpleTabsViewController#1]
First of all thank you for your awesome code. This is my official first day using Swift and your tabs are simply awesome!

Well, I slightly changed the code, so instead of small 2px marker on the bottom, I have full height marker behind every button. However, I see that there is some sort of a margin on the left and right of the label. And ?px margin between the sides of the screen and the buttons in the container.

So, how can I make the buttons' width to be 1/Nth (N = tab count)? Thanks in advance!

**Comment by bitomule** [comment]
Thanks @awedeebawe,
Maybe adding left and right constraints (NSLayoutConstraints) to container view will make the tabs take all the space.

Right now you have something like:

![1](https://cloud.githubusercontent.com/assets/1024555/7840393/7029384c-0497-11e5-941a-c1cc9f2d3f2d.png)

And you want something like:

![2](https://cloud.githubusercontent.com/assets/1024555/7840437/9e1ca496-0497-11e5-97b2-f549cd8725b7.png)

You'll need to learn about layout constraints to make this changes.

**Comment by awedeebawe** [comment]
Yeah, I know. I'm migrating from Obj-C and calculator to 21st century :D
anyway, thanks for the reply :)))

**Comment by bitomule** [comment]
No problem, hope you can find the way ;)

**Comment by awedeebawe** [comment]
Sorry for opening the issue again, but I tried to add leading and trailing constraints. It really expanded the container as you said, but I got some strange behaviour......

What am I missing? (Except essential Swift training, of course :D )

edit: I made it. I changed SimpleTabItem.swift , added one more parameter in the `createTabView` method to pass the item count, and added the needed constraints in the `setFirstTabConstraints` and `setMiddleTabConstraints` methods as follows:

```
    private func setFirstTabConstraints(){
        var calcWidth = CGFloat(tabContainer.tabsContainer.frame.size.width) / CGFloat(self.tabCount);
        let widthConstraint = NSLayoutConstraint(item: tabView, attribute: NSLayoutAttribute.Width, relatedBy: NSLayoutRelation.Equal, toItem: nil, attribute: NSLayoutAttribute.NotAnAttribute, multiplier: 1, constant: calcWidth);
        let leadingSpace = NSLayoutConstraint(item: tabView, attribute: NSLayoutAttribute.Leading, relatedBy: NSLayoutRelation.Equal, toItem: tabContainer.tabsContainer, attribute: NSLayoutAttribute.Leading, multiplier: 1, constant: 0)
        tabContainer.tabsContainer.addConstraints([widthConstraint, leadingSpace])
    }

    private func setMiddleTabConstraints(previousTab:SimpleTabItem){
        let widthConstraint = NSLayoutConstraint(item: tabView, attribute: NSLayoutAttribute.Width, relatedBy: NSLayoutRelation.Equal, toItem: previousTab.tabView, attribute: NSLayoutAttribute.Width, multiplier: 1, constant: 0);
        let leadingSpace = NSLayoutConstraint(item: tabView, attribute: NSLayoutAttribute.Leading, relatedBy: NSLayoutRelation.Equal, toItem: previousTab.tabView, attribute: NSLayoutAttribute.Trailing, multiplier: 1, constant: 0)
        tabContainer.tabsContainer.addConstraints([widthConstraint, leadingSpace])
    }
```

Then to make the container' as wide as the view controller is, I changed the `createTabsContainer` method as follows:

```
    private func createTabsContainer(){
        tabsContainer = UIView(frame: CGRect(x: 0, y: 0, width: self.view.bounds.width, height: 50))
        tabsContainer.setTranslatesAutoresizingMaskIntoConstraints(false)
        self.view.addSubview(tabsContainer)
        let centerXConstraint = NSLayoutConstraint(item: self.view, attribute: NSLayoutAttribute.CenterX, relatedBy: NSLayoutRelation.Equal, toItem: tabsContainer, attribute: NSLayoutAttribute.CenterX, multiplier: 1, constant: 0)
        let centerYConstraint = NSLayoutConstraint(item: self.view, attribute: NSLayoutAttribute.CenterY, relatedBy: NSLayoutRelation.Equal, toItem: tabsContainer, attribute: NSLayoutAttribute.CenterY, multiplier: 1, constant: -4)
        let topConstraint = NSLayoutConstraint(item: tabsContainer, attribute: NSLayoutAttribute.Top, relatedBy: NSLayoutRelation.Equal, toItem: self.view, attribute: NSLayoutAttribute.Top, multiplier: 1, constant: 0)

        let trailing = NSLayoutConstraint(item: self.view, attribute: NSLayoutAttribute.Trailing, relatedBy: NSLayoutRelation.Equal, toItem: tabsContainer, attribute: NSLayoutAttribute.Trailing, multiplier: 1, constant: 0);
        let leading = NSLayoutConstraint(item: tabsContainer, attribute: NSLayoutAttribute.Leading, relatedBy: NSLayoutRelation.Equal, toItem: self.view, attribute: NSLayoutAttribute.Leading, multiplier: 1, constant: 0);

        self.view.addConstraints([centerXConstraint,centerYConstraint,topConstraint, trailing, leading])
    }
```

and finally, I added `label.textAlignment = .Center;` in the `createTabView` method. And now I have full width tab bar container with equally wide tabs. So thank you @bitomule , your code is awesome and understandable :)))) now you can close the issue and I hope I help someone else :)))

**Comment by bitomule** [comment]
Great work! Sorry to be late but glad you found the way yourself :)
